verify github actions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -47,7 +47,7 @@ jobs:
           uses: golangci/golangci-lint-action@v6
           with:
             version: v1.55.2
-            run: golangci-lint run
+            #run: golangci-lint run
             working-directory: src/product-catalog
 
     docker:
@@ -74,7 +74,12 @@ jobs:
             context: src/product-catalog
             file: src/product-catalog/Dockerfile
             push: true
-            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}
+            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}
+
+        - name: Validate Docker secrets
+          run: |
+            [ -z "${{ secrets.DOCKER_USERNAME }}" ] && echo "Missing DOCKER_USERNAME" && exit 1
+            [ -z "${{ secrets.DOCKER_TOKEN }}" ] && echo "Missing DOCKER_TOKEN" && exit 1
 
     
     updatek8s:
